// Local exports from the supplied lab-3 Figma file.
export const wellbeingAssets = {
  libraryContainer: require('../../assets/images/wellbeing/library-Container.svg'),
  libraryContainer1: require('../../assets/images/wellbeing/library-Container1.svg'),
  libraryContainer2: require('../../assets/images/wellbeing/library-Container2.svg'),
  libraryContainer3: require('../../assets/images/wellbeing/library-Container3.svg'),
  libraryContainer4: require('../../assets/images/wellbeing/library-Container4.svg'),
  libraryContainer5: require('../../assets/images/wellbeing/library-Container5.svg'),
  articleTranquilSteamingHerbalTeaRiverStonesAndFreshEucalyptusLeafInWarmMorningSunlight: require('../../assets/images/wellbeing/article-TranquilSteamingHerbalTeaRiverStonesAndFreshEucalyptusLeafInWarmMorningSunlight.png'),
  articleButtonGoBackSvgWireframeBackArrow: require('../../assets/images/wellbeing/article-ButtonGoBackSvgWireframeBackArrow.svg'),
  articleContainer: require('../../assets/images/wellbeing/article-Container.svg'),
  articleSvg: require('../../assets/images/wellbeing/article-Svg.svg'),
  articleSvg1: require('../../assets/images/wellbeing/article-Svg1.svg'),
  breathingButtonSettingsSvg: require('../../assets/images/wellbeing/breathing-ButtonSettingsSvg.svg'),
  breathingSvg: require('../../assets/images/wellbeing/breathing-Svg.svg'),
  supportSvg: require('../../assets/images/wellbeing/support-Svg.svg'),
  supportSvg1: require('../../assets/images/wellbeing/support-Svg1.svg'),
  supportSvg2: require('../../assets/images/wellbeing/support-Svg2.svg'),
  supportSvg3: require('../../assets/images/wellbeing/support-Svg3.svg'),
  emergencyWarningIconSvg: require('../../assets/images/wellbeing/emergency-WarningIconSvg.svg'),
  emergencySvg: require('../../assets/images/wellbeing/emergency-Svg.svg'),
  emergencySvg1: require('../../assets/images/wellbeing/emergency-Svg1.svg'),
  emergencySvg2: require('../../assets/images/wellbeing/emergency-Svg2.svg'),
  directoryImage26: require('../../assets/images/wellbeing/directory-Image26.png'),
  directoryImage27: require('../../assets/images/wellbeing/directory-Image27.png'),
  directoryImage28: require('../../assets/images/wellbeing/directory-Image28.png'),
  directoryImage34: require('../../assets/images/wellbeing/directory-Image34.png'),
  directoryFrame: require('../../assets/images/wellbeing/directory-Frame.svg'),
  moodImage18: require('../../assets/images/wellbeing/mood-Image18.png'),
  moodImage21: require('../../assets/images/wellbeing/mood-Image21.png'),
  moodImage11: require('../../assets/images/wellbeing/mood-Image11.png'),
  moodImage22: require('../../assets/images/wellbeing/mood-Image22.png'),
  moodImage23: require('../../assets/images/wellbeing/mood-Image23.png'),
  moodImage24: require('../../assets/images/wellbeing/mood-Image24.png'),
} as const;
